name: build
on:
  push:
    branches:
      - master
jobs:
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Build Android Release APK
        run: |
          ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - name: Build Android Release Bundle
        run: |
          ./gradlew bundleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.bundle
          path: android/app/build/outputs/bundle/release/
